stages:
    - check_format
    - tests
    - firmware
    - update-tsvf

variables:
    GIT_SUBMODULE_STRATEGY: recursive

check_format:
    stage: check_format
    image: px4io/px4-dev-nuttx:2018-09-28
    tags:
        - docker
    script:
        - make check_format

tests:
    stage: tests
    image: px4io/px4-dev-simulation:2018-09-28
    tags:
        - docker
    script:
        - make tests

firmware:
    stage: firmware
    image: px4io/px4-dev-nuttx:2018-09-28
    tags:
        - docker
    script:
        # - .gitlab-scripts/deploy-firmware
        - make px4fmu-v4_default
    artifacts:
        expire_in: 1 week
        paths:
            - /builds/Teal/Flight-Stack/build/nuttx_px4fmu-v4_default/px4fmu-v4_default.px4

# update-teal-software-verison-file:
#     image: tealdrones/teal-software-version-file-manager
#     stage: update-tsvf
#     only:
#         - dev
#         - test
#         - master
#     tags:
#         - deploy
#     script:
#         - .gitlab-scripts/update-software-version-file

