stages:
    - check_format
    - tests
    - firmware
    - deploy
    - update-tsvf

variables:
    GIT_SUBMODULE_STRATEGY: recursive

check_format:
    stage: check_format
    image: px4io/px4-dev-nuttx:2018-09-28
    tags:
        - docker
    script:
        - make check_format

test:
    stage: tests
    image: px4io/px4-dev-simulation:2018-09-28
    tags:
        - docker
    script:
        - make tests

build-firmware:
    stage: firmware
    image: px4io/px4-dev-nuttx:2018-09-28
    tags:
        - docker
    script:
        - make px4fmu-v4_default
    artifacts:
        expire_in: 1 week
        paths:
            - ./build/nuttx_px4fmu-v4_default/px4fmu-v4_default.px4

create-and-deploy-px4-tse:
    stage: deploy
    image: px4io/px4-dev-nuttx:2018-09-28
    tags:
        - deploy
    only:
        - dev
        - test
        - master
    script:
        - .gitlab-scripts/deploy-firmware
    artifacts:
        expire_in: 1 week
        paths:
            - "TealSEI/*.tse.jsq"

update-teal-software-verison-file:
    image: tealdrones/teal-software-version-file-manager
    stage: update-tsvf
    only:
        - dev
        - test
    tags:
        - deploy
    script:
        - .gitlab-scripts/update-software-version-file
