#!/bin/bash
project_root="${CI_PROJECT_DIR}"
working_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Get version from version file.
version_file_path="$working_dir/version"
if [ -f "$version_file_path" ]; then
    version=$(cat $version_file_path)
else
    echo "Could not read version file at $working_dir/version."
    exit 1
fi

branch="$CI_COMMIT_REF_NAME"

# Add (and rename) the px4 binary to the payload directory.
px4_bin_path="${project_root}/build/nuttx_px4fmu-v4_default/px4fmu-v4_default.px4"
rsync -aPvz $px4_bin_path $working_dir/payload/v${version}.px4 || exit 1

# Generate TSE file.
$working_dir/TealSEI/generateTSEGitLab $working_dir/payload Teal-PX4-"${version}" || exit 1

# Deploy the TSE file.
$working_dir/SharedGitLabUtilities/deploy-artifact-to-s3 $(ls *.tse.jsq) TealPX4 $branch || exit 1

# Deploy the .px4 file.
$working_dir/SharedGitLabUtilities/deploy-artifact-to-s3 $working_dir/payload/v${version}.px4 TealPX4 $branch || exit 1
