#!/bin/bash
project_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Get version from version file.
version_file_path="$project_root/version"
if [ -f "$version_file_path" ]; then
    version=$(cat $version_file_path)
else
    echo "Could not read version file at $project_root/version."
    exit 1
fi

# Generate the px4 binary.
# make px4fmu-v4_default || exit 1

# Add (and rename) the px4 binary to the payload directory.
px4_bin_path="/builds/Teal/Flight-Stack/build/nuttx_px4fmu-v4_default/px4fmu-v4_default.px4"
rsync -aPvz $px4_bin_path $project_root/payload/v${version}.px4 || exit 1

# Generate TSE file.
# TealSEI/.gitlab-scripts/generate-tse-file payload Teal-PX4-"${version}".tse.jsq || exit 1
cd TealSEI
.gitlab-scripts/generate-tse-file ./ Delete-Me-Teal-PX4-"${version}".tse.jsq || exit 1

# Deploy the TSE file.
.gitlab-scripts/deploy-artifact-to-s3 TealPX4 *.tse.jsq || exit 1

# Deploy the .px4 file.
.gitlab-scripts/deploy-artifact-to-s3 TealPX4 *.px4 || exit 1
cd project_root