#!/bin/bash
# @author Darin Stoker
# @date 3/1/18

# Parameter check.
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "Usage: $0 <path-of-file-to-upload> <component-name> <branch>"
    exit 2
fi

FILEPATH="$1"
COMPONENT="$2"
BRANCH="$3"

# Decide which S3 folder to use based on branch.
if [[ "$BRANCH" = "dev" ]]; then
    SUBFOLDER="unstable"
elif [[ "$BRANCH" = "test" ]]; then
    SUBFOLDER="stable"
elif [[ "$BRANCH" = "master" ]]; then
    SUBFOLDER="production"
else
    echo "Error. Should only run on dev, test, or master branches."
    exit 1
fi

# Send file up to S3.
echo "Sending ${FILEPATH} to s3://version.tealdrones.com/${COMPONENT}/${SUBFOLDER}/"
aws s3 cp $FILEPATH s3://version.tealdrones.com/$COMPONENT/$SUBFOLDER/

# Create new LATEST file and send it up to S3.
FILENAME="$(basename $FILEPATH | tr -d '/')"
FILE_EXT=$(echo "${FILENAME##*.}")
LATEST_FILENAME="LATEST_${FILE_EXT^^}"

touch $LATEST_FILENAME
echo "https://s3.amazonaws.com/version.tealdrones.com/${COMPONENT}/${SUBFOLDER}/${FILENAME}" > $LATEST_FILENAME
aws s3 cp $LATEST_FILENAME s3://version.tealdrones.com/$COMPONENT/$SUBFOLDER/
