#!/bin/bash
#
# @author Darin Stoker
# @date 8/22/18

project_root="${CI_PROJECT_DIR}"
working_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

version_file_url_dev="http://version.tealdrones.com/tealone/teal-software-versions-dev.json/"
version_file_url_test="http://version.tealdrones.com/tealone/teal-software-versions-test.json/"
version_file_url_master="http://version.tealdrones.com/tealone/teal-software-versions-pre-master.json/"

asset_name=$(ls $project_root | grep -e ".*.tse.jsq")
if [ -z $asset_name]; then
    echo "No TSE files found in the project root."
    exit 1
fi

asset_filepath="${project_root}/${asset_name}"
asset_md5=$(md5sum $asset_filepath | awk '{print $1}')
asset_version=$(echo $asset_name | grep -Eio "[0-9]+\.[0-9]+\.[0-9]+")
asset_url_dev="https://s3.amazonaws.com/version.tealdrones.com/TealPX4/unstable/${asset_name}"
asset_url_test="https://s3.amazonaws.com/version.tealdrones.com/TealPX4/stable/${asset_name}"
asset_url_master="https://s3.amazonaws.com/version.tealdrones.com/TealPX4/production/${asset_name}"
# asset_requirements="{"Versions":}"
python3 $working_dir/update-tsv-file $version_file_url_dev $asset_filepath $asset_md5 $asset_version $asset_url_dev "None" || exit $?
python3 $working_dir/update-tsv-file $version_file_url_test $asset_filepath $asset_md5 $asset_version $asset_url_test "None" || exit $?
python3 $working_dir/update-tsv-file $version_file_url_master $asset_filepath $asset_md5 $asset_version $asset_url_master "None" || exit $?
