#!/bin/bash
#
# @author Darin Stoker
# @date 8/22/18

PROJECT_ROOT="${CI_PROJECT_DIR}"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Set up parameters for update-tsv-file
BRANCH="$CI_COMMIT_REF_NAME"

if [[ "$BRANCH" = "dev" || "$BRANCH" = "ci" ]]; then
    BRANCH="dev"
    SUBFOLDER="unstable"
elif [[ "$BRANCH" = "test" ]]; then
    SUBFOLDER="stable"
elif [[ "$BRANCH" = "master" ]]; then
    SUBFOLDER="production"
else
    echo "Error. Should only run on dev, test, or master branches."
    exit 1
fi

VERSION_FILE_URL="http://version.tealdrones.com/tealone/teal-software-versions-${BRANCH}.json/"

ASSET_NAME=$(ls $PROJECT_ROOT | grep -e ".*.tse.jsq")
if [ -z $ASSET_NAME]; then
    echo "No TSE files found in the project root."
    exit 1
fi

ASSET_FILEPATH="${PROJECT_ROOT}/${ASSET_NAME}"
ASSET_MD5=$(md5sum $ASSET_FILEPATH | awk '{print $1}')
ASSET_VERSION=$(echo $ASSET_NAME | grep -Eio "[0-9]+.[0-9]+.[0-9]+")
ASSET_URL="https://s3.amazonaws.com/version.tealdrones.com/TealPX4/${SUBFOLDER}/${ASSET_NAME}"
# ASSET_REQUIREMENTS="{"Versions":}"
python3 $SCRIPT_DIR/update-tsv-file $VERSION_FILE_URL $ASSET_FILEPATH $ASSET_MD5 $ASSET_VERSION $ASSET_URL $ASSET_REQUIREMENTS "None" || exit $?
